// 创建数据 数据集合
const data = {
  // 外套的数据
  coat: [
    {
      coatname: "时崎狂三风衣外套-厚款",
      coatimg: "imgs/商品外套imgs/时崎狂三外套.jpg",
      coatmoney: "184",
      title: "coat",
      id: 100001,
      climgs: [
        "imgs/商品详情imgs/时崎狂三1.jpg",
        "imgs/商品详情imgs/时崎狂三2.jpg",
        "imgs/商品详情imgs/时崎狂三3.jpg",
        "imgs/商品详情imgs/时崎狂三4.jpg",
        "imgs/商品详情imgs/时崎狂三5.jpg",
        "imgs/商品详情imgs/时崎狂三6.jpg",
        "imgs/商品详情imgs/时崎狂三7.jpg",
        "imgs/商品详情imgs/时崎狂三8.jpg",
        "imgs/商品详情imgs/时崎狂三9.jpg",
      ],
    },
    {
      coatname: "星尘男女服装外套",
      coatimg: "imgs/商品外套imgs/星尘男女服装外套1.jpg",
      coatmoney: "188",
      title: "coat",
      id: 100002,
      climgs: [
        "imgs/商品详情imgs/星尘男女服装外套1.jpg",
        "imgs/商品详情imgs/星尘男女服装外套2.jpg",
        "imgs/商品详情imgs/星尘男女服装外套3.jpg",
        "imgs/商品详情imgs/星尘男女服装外套4.jpg",
        "imgs/商品详情imgs/星尘男女服装外套5.jpg",
        "imgs/商品详情imgs/星尘男女服装外套6.jpg",
        "imgs/商品详情imgs/星尘男女服装外套7.jpg",
        "imgs/商品详情imgs/星尘男女服装外套8.jpg",
        "imgs/商品详情imgs/星尘男女服装外套9.jpg",
      ],
    },
    {
      coatname: "星尘星间游侠外套",
      coatimg: "imgs/商品外套imgs/星尘男女服装外套2.jpg",
      coatmoney: "228",
      title: "coat",
      id: 100003,
      climgs: [
        "imgs/商品详情imgs/星尘星间游侠外套1.jpg",
        "imgs/商品详情imgs/星尘星间游侠外套2.jpg",
        "imgs/商品详情imgs/星尘星间游侠外套3.jpg",
        "imgs/商品详情imgs/星尘星间游侠外套4.jpg",
        "imgs/商品详情imgs/星尘星间游侠外套5.jpg",
        "imgs/商品详情imgs/星尘星间游侠外套6.jpg",
        "imgs/商品详情imgs/星尘星间游侠外套7.jpg",
        "imgs/商品详情imgs/星尘星间游侠外套8.jpg",
        "imgs/商品详情imgs/星尘星间游侠外套9.jpg",
      ],
    },
    {
      coatname: "星尘闪耀地平线款外套",
      coatimg: "imgs/商品外套imgs/星尘男女服装外套3.jpg",
      coatmoney: "208",
      title: "coat",
      id: 100004,
      climgs: [
        "imgs/商品详情imgs/星尘闪耀地平线款外套1.jpg",
        "imgs/商品详情imgs/星尘闪耀地平线款外套2.jpg",
        "imgs/商品详情imgs/星尘闪耀地平线款外套3.jpg",
        "imgs/商品详情imgs/星尘闪耀地平线款外套4.jpg",
        "imgs/商品详情imgs/星尘闪耀地平线款外套5.jpg",
        "imgs/商品详情imgs/星尘闪耀地平线款外套6.jpg",
        "imgs/商品详情imgs/星尘闪耀地平线款外套7.jpg",
        "imgs/商品详情imgs/星尘闪耀地平线款外套8.jpg",
        "imgs/商品详情imgs/星尘闪耀地平线款外套9.jpg",
      ],
    },
    {
      coatname: "星尘牛仔外套",
      coatimg: "imgs/商品外套imgs/星尘男女服装外套4.jpg",
      coatmoney: "229",
      title: "coat",
      id: 100005,
      climgs: [
        "imgs/商品详情imgs/星尘牛仔外套1.jpg",
        "imgs/商品详情imgs/星尘牛仔外套2.jpg",
        "imgs/商品详情imgs/星尘牛仔外套3.jpg",
        "imgs/商品详情imgs/星尘牛仔外套4.jpg",
        "imgs/商品详情imgs/星尘牛仔外套5.jpg",
        "imgs/商品详情imgs/星尘牛仔外套6.jpg",
        "imgs/商品详情imgs/星尘牛仔外套7.jpg",
        "imgs/商品详情imgs/星尘牛仔外套8.jpg",
        "imgs/商品详情imgs/星尘牛仔外套9.jpg",
        "imgs/商品详情imgs/星尘牛仔外套10.jpg",
        "imgs/商品详情imgs/星尘牛仔外套11.jpg",
        "imgs/商品详情imgs/星尘牛仔外套12.jpg",
        "imgs/商品详情imgs/星尘牛仔外套13.jpg",
        "imgs/商品详情imgs/星尘牛仔外套14.jpg",
        "imgs/商品详情imgs/星尘牛仔外套15.jpg",
        "imgs/商品详情imgs/星尘牛仔外套16.jpg",
      ],
    },
    {
      coatname: "星尘中长款概念风衣外套",
      coatimg: "imgs/商品外套imgs/星尘中长款概念风衣外套.jpg",
      coatmoney: "329",
      title: "coat",
      id: 100006,
      climgs: [
        "imgs/商品详情imgs/星尘中长款概念风衣外套1.jpg",
        "imgs/商品详情imgs/星尘中长款概念风衣外套2.jpg",
        "imgs/商品详情imgs/星尘中长款概念风衣外套3.jpg",
        "imgs/商品详情imgs/星尘中长款概念风衣外套4.jpg",
        "imgs/商品详情imgs/星尘中长款概念风衣外套5.jpg",
        "imgs/商品详情imgs/星尘中长款概念风衣外套6.jpg",
        "imgs/商品详情imgs/星尘中长款概念风衣外套7.jpg",
        "imgs/商品详情imgs/星尘中长款概念风衣外套8.jpg",
        "imgs/商品详情imgs/星尘中长款概念风衣外套9.jpg",
        "imgs/商品详情imgs/星尘中长款概念风衣外套10.jpg",
        "imgs/商品详情imgs/星尘中长款概念风衣外套11.jpg",
      ],
    },
    {
      coatname: "星尘文字潮流主题棉外套",
      coatimg: "imgs/商品外套imgs/星尘文字潮流主题棉外套.jpg",
      coatmoney: "338",
      title: "coat",
      id: 100007,
      climgs: [
        "imgs/商品详情imgs/星尘文字潮流主题棉外套1.jpg",
        "imgs/商品详情imgs/星尘文字潮流主题棉外套2.jpg",
        "imgs/商品详情imgs/星尘文字潮流主题棉外套3.jpg",
        "imgs/商品详情imgs/星尘文字潮流主题棉外套4.jpg",
        "imgs/商品详情imgs/星尘文字潮流主题棉外套5.jpg",
        "imgs/商品详情imgs/星尘文字潮流主题棉外套6.jpg",
        "imgs/商品详情imgs/星尘文字潮流主题棉外套7.jpg",
        "imgs/商品详情imgs/星尘文字潮流主题棉外套8.jpg",
        "imgs/商品详情imgs/星尘文字潮流主题棉外套9.jpg",
        "imgs/商品详情imgs/星尘文字潮流主题棉外套10.jpg",
        "imgs/商品详情imgs/星尘文字潮流主题棉外套11.jpg",
      ],
    },
    {
      coatname: "星尘羽绒服",
      coatimg: "imgs/商品外套imgs/星尘羽绒服.jpg",
      coatmoney: "229",
      title: "coat",
      id: 100008,
      climgs: [
        "imgs/商品详情imgs/星尘羽绒服1.jpg",
        "imgs/商品详情imgs/星尘羽绒服2.jpg",
        "imgs/商品详情imgs/星尘羽绒服3.jpg",
        "imgs/商品详情imgs/星尘羽绒服4.jpg",
        "imgs/商品详情imgs/星尘羽绒服5.jpg",
        "imgs/商品详情imgs/星尘羽绒服6.jpg",
        "imgs/商品详情imgs/星尘羽绒服7.jpg",
        "imgs/商品详情imgs/星尘羽绒服8.jpg",
        "imgs/商品详情imgs/星尘羽绒服9.jpg",
      ],
    },
    {
      coatname: "星尘星之命运外套",
      coatimg: "imgs/商品外套imgs/星尘星之命运外套.jpg",
      coatmoney: "209",
      title: "coat",
      id: 100009,
      climgs: [
        "imgs/商品详情imgs/星尘星之命运外套1.jpg",
        "imgs/商品详情imgs/星尘星之命运外套2.jpg",
        "imgs/商品详情imgs/星尘星之命运外套3.jpg",
        "imgs/商品详情imgs/星尘星之命运外套4.jpg",
        "imgs/商品详情imgs/星尘星之命运外套5.jpg",
        "imgs/商品详情imgs/星尘星之命运外套6.jpg",
        "imgs/商品详情imgs/星尘星之命运外套7.jpg",
        "imgs/商品详情imgs/星尘星之命运外套8.jpg",
        "imgs/商品详情imgs/星尘星之命运外套9.jpg",
      ],
    },
    {
      coatname: "星尘连帽套头外套",
      coatimg: "imgs/商品外套imgs/星尘连帽套头卫衣.jpg",
      coatmoney: "158",
      title: "coat",
      id: 100010,
      climgs: [
        "imgs/商品详情imgs/星尘连帽套头卫衣.jpg",
        "imgs/商品详情imgs/星尘连帽套头卫衣2.jpg",
        "imgs/商品详情imgs/星尘连帽套头卫衣3.jpg",
        "imgs/商品详情imgs/星尘连帽套头卫衣4.jpg",
        "imgs/商品详情imgs/星尘连帽套头卫衣5.jpg",
        "imgs/商品详情imgs/星尘连帽套头卫衣6.jpg",
        "imgs/商品详情imgs/星尘连帽套头卫衣7.jpg",
        "imgs/商品详情imgs/星尘连帽套头卫衣8.jpg",
        "imgs/商品详情imgs/星尘连帽套头卫衣9.jpg",
        "imgs/商品详情imgs/星尘连帽套头卫衣10.jpg",
      ],
    },
    {
      coatname: "琪亚娜白练外套",
      coatimg: "imgs/商品外套imgs/琪亚娜白练卫衣.jpg",
      coatmoney: "289",
      title: "coat",
      id: 100011,
      climgs: [
        "imgs/商品详情imgs/琪亚娜白练卫衣1.jpg",
        "imgs/商品详情imgs/琪亚娜白练卫衣2.jpg",
        "imgs/商品详情imgs/琪亚娜白练卫衣3.jpg",
        "imgs/商品详情imgs/琪亚娜白练卫衣4.jpg",
        "imgs/商品详情imgs/琪亚娜白练卫衣5.jpg",
      ],
    },
    {
      coatname: "理之律者主题外套",
      coatimg: "imgs/商品外套imgs/理之律者主题卫衣.jpg",
      coatmoney: "199",
      title: "coat",
      id: 100012,
      climgs: [
        "imgs/商品详情imgs/理之律者主题卫衣1.jpg",
        "imgs/商品详情imgs/理之律者主题卫衣2.jpg",
        "imgs/商品详情imgs/理之律者主题卫衣3.jpg",
        "imgs/商品详情imgs/理之律者主题卫衣4.jpg",
        "imgs/商品详情imgs/理之律者主题卫衣5.jpg",
        "imgs/商品详情imgs/理之律者主题卫衣6.jpg",
      ],
    },
    {
      coatname: "狂热蓝调Δ主题外套",
      coatimg: "imgs/商品外套imgs/狂热蓝调Δ主题卫衣.jpg",
      coatmoney: "199",
      title: "coat",
      id: 100013,
      climgs: [
        "imgs/商品详情imgs/狂热蓝调Δ主题卫衣1.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题卫衣2.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题卫衣3.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题卫衣4.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题卫衣5.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题卫衣6.jpg",
      ],
    },
    {
      coatname: "失落迷迭主题外套",
      coatimg: "imgs/商品外套imgs/丽塔失落迷迭主题外套.jpg",
      coatmoney: "289",
      title: "coat",
      id: 100014,
      climgs: [
        "imgs/商品详情imgs/失落迷迭主题外套1.jpg",
        "imgs/商品详情imgs/失落迷迭主题外套2.jpg",
        "imgs/商品详情imgs/失落迷迭主题外套3.jpg",
        "imgs/商品详情imgs/失落迷迭主题外套4.jpg",
        "imgs/商品详情imgs/失落迷迭主题外套5.jpg",
        "imgs/商品详情imgs/失落迷迭主题外套6.jpg",
      ],
    },
    {
      coatname: "薪炎之律者主题外套",
      coatimg: "imgs/商品外套imgs/薪炎之律者主题外套.jpg",
      coatmoney: "499",
      title: "coat",
      id: 100015,
      climgs: [
        "imgs/商品详情imgs/薪炎之律者主题外套1.jpg",
        "imgs/商品详情imgs/薪炎之律者主题外套2.jpg",
        "imgs/商品详情imgs/薪炎之律者主题外套3.jpg",
        "imgs/商品详情imgs/薪炎之律者主题外套4.jpg",
        "imgs/商品详情imgs/薪炎之律者主题外套5.jpg",
        "imgs/商品详情imgs/薪炎之律者主题外套6.jpg",
      ],
    },
  ],

  // T恤的数据
  tshirt: [
    {
      tshirtname: "星尘正版周边T恤",
      tshirtimg: "imgs/商品T恤imgs/星尘T恤.jpg",
      tshirtmoney: "129",
      title: "tshirt",
      id: 200001,
      climgs: [
        "imgs/商品详情imgs/星尘1.jpg",
        "imgs/商品详情imgs/星尘2.jpg",
        "imgs/商品详情imgs/星尘3.jpg",
        "imgs/商品详情imgs/星尘4.jpg",
        "imgs/商品详情imgs/星尘5.jpg",
        "imgs/商品详情imgs/星尘6.jpg",
        "imgs/商品详情imgs/星尘7.jpg",
        "imgs/商品详情imgs/星尘8.jpg",
        "imgs/商品详情imgs/星尘9.jpg",
        "imgs/商品详情imgs/星尘10.jpg",
        "imgs/商品详情imgs/星尘11.jpg",
        "imgs/商品详情imgs/星尘12.jpg",
        "imgs/商品详情imgs/星尘13.jpg",
        "imgs/商品详情imgs/星尘14.jpg",
      ],
    },
    {
      tshirtname: "初音未来39感谢日短袖T恤",
      tshirtimg: "imgs/商品T恤imgs/初音未来T恤1.jpg",
      tshirtmoney: "139",
      title: "tshirt",
      id: 200002,
      climgs: [
        "imgs/商品详情imgs/初音未来感谢日1.jpg",
        "imgs/商品详情imgs/初音未来感谢日2.jpg",
        "imgs/商品详情imgs/初音未来感谢日3.jpg",
        "imgs/商品详情imgs/初音未来感谢日4.jpg",
        "imgs/商品详情imgs/初音未来感谢日5.jpg",
        "imgs/商品详情imgs/初音未来感谢日6.jpg",
        "imgs/商品详情imgs/初音未来感谢日7.jpg",
        "imgs/商品详情imgs/初音未来感谢日8.jpg",
        "imgs/商品详情imgs/初音未来感谢日9.jpg",
      ],
    },
    {
      tshirtname: "初音未来夏季服装T恤",
      tshirtimg: "imgs/商品T恤imgs/初音未来T恤2.jpg",
      tshirtmoney: "136",
      title: "tshirt",
      id: 200003,
      climgs: [
        "imgs/商品详情imgs/初音未来夏季服装T恤1.jpg",
        "imgs/商品详情imgs/初音未来夏季服装T恤2.jpg",
        "imgs/商品详情imgs/初音未来夏季服装T恤3.jpg",
        "imgs/商品详情imgs/初音未来夏季服装T恤4.jpg",
        "imgs/商品详情imgs/初音未来夏季服装T恤5.jpg",
        "imgs/商品详情imgs/初音未来夏季服装T恤6.jpg",
        "imgs/商品详情imgs/初音未来夏季服装T恤7.jpg",
        "imgs/商品详情imgs/初音未来夏季服装T恤8.jpg",
      ],
    },
    {
      tshirtname: "初音未来T恤动漫服装",
      tshirtimg: "imgs/商品T恤imgs/初音未来T恤3.jpg",
      tshirtmoney: "139",
      title: "tshirt",
      id: 200004,
      climgs: [
        "imgs/商品详情imgs/初音未来T恤动漫服装.jpg",
        "imgs/商品详情imgs/初音未来T恤动漫服装1.jpg",
        "imgs/商品详情imgs/初音未来T恤动漫服装2.jpg",
        "imgs/商品详情imgs/初音未来T恤动漫服装3.jpg",
        "imgs/商品详情imgs/初音未来T恤动漫服装4.jpg",
        "imgs/商品详情imgs/初音未来T恤动漫服装5.jpg",
        "imgs/商品详情imgs/初音未来T恤动漫服装6.jpg",
        "imgs/商品详情imgs/初音未来T恤动漫服装7.jpg",
        "imgs/商品详情imgs/初音未来T恤动漫服装8.jpg",
        "imgs/商品详情imgs/初音未来T恤动漫服装9.jpg",
        "imgs/商品详情imgs/初音未来T恤动漫服装10.jpg",
      ],
    },
    {
      tshirtname: "初音未来打底衫",
      tshirtimg: "imgs/商品T恤imgs/初音未来T恤.jpg",
      tshirtmoney: "149",
      title: "tshirt",
      id: 200005,
      climgs: [
        "imgs/商品详情imgs/初音未来打底衫1.jpg",
        "imgs/商品详情imgs/初音未来打底衫2.jpg",
        "imgs/商品详情imgs/初音未来打底衫3.jpg",
        "imgs/商品详情imgs/初音未来打底衫4.jpg",
        "imgs/商品详情imgs/初音未来打底衫5.jpg",
        "imgs/商品详情imgs/初音未来打底衫6.jpg",
        "imgs/商品详情imgs/初音未来打底衫7.jpg",
        "imgs/商品详情imgs/初音未来打底衫8.jpg",
        "imgs/商品详情imgs/初音未来打底衫9.jpg",
        "imgs/商品详情imgs/初音未来打底衫10.jpg",
        "imgs/商品详情imgs/初音未来打底衫11.jpg",
      ],
    },
    {
      tshirtname: "星尘音乐游戏主题T恤",
      tshirtimg: "imgs/商品T恤imgs/星尘T恤2.jpg",
      tshirtmoney: "138",
      title: "tshirt",
      id: 200006,
      climgs: [
        "imgs/商品详情imgs/星尘音乐游戏主题T恤1.jpg",
        "imgs/商品详情imgs/星尘音乐游戏主题T恤2.jpg",
        "imgs/商品详情imgs/星尘音乐游戏主题T恤3.jpg",
        "imgs/商品详情imgs/星尘音乐游戏主题T恤4.jpg",
        "imgs/商品详情imgs/星尘音乐游戏主题T恤5.jpg",
        "imgs/商品详情imgs/星尘音乐游戏主题T恤6.jpg",
        "imgs/商品详情imgs/星尘音乐游戏主题T恤7.jpg",
        "imgs/商品详情imgs/星尘音乐游戏主题T恤8.jpg",
        "imgs/商品详情imgs/星尘音乐游戏主题T恤9.jpg",
      ],
    },
    {
      tshirtname: "星尘T恤摇滚主题",
      tshirtimg: "imgs/商品T恤imgs/星尘T恤4.jpg",
      tshirtmoney: "188",
      title: "tshirt",
      id: 200007,
      climgs: [
        "imgs/商品详情imgs/星尘T恤摇滚主题1.jpg",
        "imgs/商品详情imgs/星尘T恤摇滚主题2.jpg",
        "imgs/商品详情imgs/星尘T恤摇滚主题3.jpg",
        "imgs/商品详情imgs/星尘T恤摇滚主题4.jpg",
        "imgs/商品详情imgs/星尘T恤摇滚主题5.jpg",
        "imgs/商品详情imgs/星尘T恤摇滚主题6.jpg",
      ],
    },
    {
      tshirtname: "星尘夏季T恤",
      tshirtimg: "imgs/商品T恤imgs/星尘夏季T恤.jpg",
      tshirtmoney: "138",
      title: "tshirt",
      id: 200008,
      climgs: [
        "imgs/商品详情imgs/星尘夏季T恤1.jpg",
        "imgs/商品详情imgs/星尘夏季T恤2.jpg",
        "imgs/商品详情imgs/星尘夏季T恤3.jpg",
        "imgs/商品详情imgs/星尘夏季T恤4.jpg",
        "imgs/商品详情imgs/星尘夏季T恤5.jpg",
        "imgs/商品详情imgs/星尘夏季T恤6.jpg",
        "imgs/商品详情imgs/星尘夏季T恤7.jpg",
        "imgs/商品详情imgs/星尘夏季T恤8.jpg",
        "imgs/商品详情imgs/星尘夏季T恤9.jpg",
        "imgs/商品详情imgs/星尘夏季T恤10.jpg",
        "imgs/商品详情imgs/星尘夏季T恤11.jpg",
      ],
    },
    {
      tshirtname: "狂热蓝调Δ主题长袖T恤",
      tshirtimg: "imgs/商品T恤imgs/狂热蓝调Δ主题长袖T恤.jpg",
      tshirtmoney: "149",
      title: "tshirt",
      id: 200009,
      climgs: [
        "imgs/商品详情imgs/狂热蓝调Δ主题长袖T恤1.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题长袖T恤2.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题长袖T恤3.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题长袖T恤4.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题长袖T恤5.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题长袖T恤6.jpg",
      ],
    },
    {
      tshirtname: "崩坏3T恤",
      tshirtimg: "imgs/商品T恤imgs/崩坏3T恤.jpg",
      tshirtmoney: "139",
      title: "tshirt",
      id: 2000010,
      climgs: [
        "imgs/商品详情imgs/崩坏3T恤1.jpg",
        "imgs/商品详情imgs/崩坏3T恤2.jpg",
        "imgs/商品详情imgs/崩坏3T恤3.jpg",
        "imgs/商品详情imgs/崩坏3T恤4.jpg",
        "imgs/商品详情imgs/崩坏3T恤5.jpg",
        "imgs/商品详情imgs/崩坏3T恤6.jpg",
      ],
    },
    {
      tshirtname: "破晓强袭长袖T恤",
      tshirtimg: "imgs/商品T恤imgs/破晓强袭长袖T恤.jpg",
      tshirtmoney: "149",
      title: "tshirt",
      id: 2000011,
      climgs: [
        "imgs/商品详情imgs/破晓强袭长袖T恤1.jpg",
        "imgs/商品详情imgs/破晓强袭长袖T恤2.jpg",
        "imgs/商品详情imgs/破晓强袭长袖T恤3.jpg",
        "imgs/商品详情imgs/破晓强袭长袖T恤4.jpg",
        "imgs/商品详情imgs/破晓强袭长袖T恤5.jpg",
        "imgs/商品详情imgs/破晓强袭长袖T恤6.jpg",
      ],
    },
    {
      tshirtname: "深渊印象主题长袖T恤",
      tshirtimg: "imgs/商品T恤imgs/深渊印象主题长袖T恤.jpg",
      tshirtmoney: "149",
      title: "tshirt",
      id: 2000012,
      climgs: [
        "imgs/商品详情imgs/深渊印象主题长袖T恤1.jpg",
        "imgs/商品详情imgs/深渊印象主题长袖T恤2.jpg",
        "imgs/商品详情imgs/深渊印象主题长袖T恤3.jpg",
        "imgs/商品详情imgs/深渊印象主题长袖T恤4.jpg",
        "imgs/商品详情imgs/深渊印象主题长袖T恤5.jpg",
        "imgs/商品详情imgs/深渊印象主题长袖T恤6.jpg",
      ],
    },
    {
      tshirtname: "崩坏印象T恤",
      tshirtimg: "imgs/商品T恤imgs/崩坏印象T恤.jpg",
      tshirtmoney: "109",
      title: "tshirt",
      id: 2000013,
      climgs: [
        "imgs/商品详情imgs/崩坏印象T恤1.jpg",
        "imgs/商品详情imgs/崩坏印象T恤2.jpg",
        "imgs/商品详情imgs/崩坏印象T恤3.jpg",
        "imgs/商品详情imgs/崩坏印象T恤4.jpg",
        "imgs/商品详情imgs/崩坏印象T恤5.jpg",
        "imgs/商品详情imgs/崩坏印象T恤6.jpg",
      ],
    },
    {
      tshirtname: "文字系列印象短袖",
      tshirtimg: "imgs/商品T恤imgs/文字系列印象短袖.jpg",
      tshirtmoney: "99",
      title: "tshirt",
      id: 2000014,
      climgs: [
        "imgs/商品详情imgs/文字系列印象短袖1.jpg",
        "imgs/商品详情imgs/文字系列印象短袖2.jpg",
        "imgs/商品详情imgs/文字系列印象短袖3.jpg",
        "imgs/商品详情imgs/文字系列印象短袖4.jpg",
        "imgs/商品详情imgs/文字系列印象短袖5.jpg",
      ],
    },
    {
      tshirtname: "花嫁系列T恤",
      tshirtimg: "imgs/商品T恤imgs/花嫁系列T恤.jpg",
      tshirtmoney: "99",
      title: "tshirt",
      id: 2000015,
      climgs: [
        "imgs/商品详情imgs/花嫁系列T恤1.jpg",
        "imgs/商品详情imgs/花嫁系列T恤2.jpg",
        "imgs/商品详情imgs/花嫁系列T恤3.jpg",
        "imgs/商品详情imgs/花嫁系列T恤4.jpg",
      ],
    },
    {
      tshirtname: "角色印花T恤",
      tshirtimg: "imgs/商品T恤imgs/角色印花T恤.jpg",
      tshirtmoney: "99",
      title: "tshirt",
      id: 2000016,
      climgs: [
        "imgs/商品详情imgs/角色印花T恤1.jpg",
        "imgs/商品详情imgs/角色印花T恤2.jpg",
        "imgs/商品详情imgs/角色印花T恤3.jpg",
        "imgs/商品详情imgs/角色印花T恤4.jpg",
        "imgs/商品详情imgs/角色印花T恤5.jpg",
      ],
    },
    {
      tshirtname: "星尘心之音T恤",
      tshirtimg: "imgs/商品T恤imgs/星尘T恤3.jpg",
      tshirtmoney: "188",
      title: "tshirt",
      id: 2000017,
      climgs: [
        "imgs/商品详情imgs/星尘心之音T恤.jpg",
        "imgs/商品详情imgs/星尘心之音T恤1.jpg",
        "imgs/商品详情imgs/星尘心之音T恤2.jpg",
        "imgs/商品详情imgs/星尘心之音T恤3.jpg",
        "imgs/商品详情imgs/星尘心之音T恤4.jpg",
        "imgs/商品详情imgs/星尘心之音T恤5.jpg",
        "imgs/商品详情imgs/星尘心之音T恤6.jpg",
        "imgs/商品详情imgs/星尘心之音T恤7.jpg",
        "imgs/商品详情imgs/星尘心之音T恤8.jpg",
      ],
    },
  ],

  // 裤子的数据
  boots: [
    {
      bootsname: "初音未来正版周边裤子",
      bootsimg: "imgs/商品裤子imgs/初音未来.jpg",
      bootsmoney: "208",
      title: "boots",
      id: 300001,
      climgs: [
        "imgs/商品详情imgs/初音裤子1.jpg",
        "imgs/商品详情imgs/初音裤子2.jpg",
        "imgs/商品详情imgs/初音裤子3.jpg",
        "imgs/商品详情imgs/初音裤子4.jpg",
        "imgs/商品详情imgs/初音裤子5.jpg",
        "imgs/商品详情imgs/初音裤子6.jpg",
        "imgs/商品详情imgs/初音裤子7.jpg",
        "imgs/商品详情imgs/初音裤子8.jpg",
        "imgs/商品详情imgs/初音裤子9.jpg",
        "imgs/商品详情imgs/初音裤子10.jpg",
        "imgs/商品详情imgs/初音裤子11.jpg",
        "imgs/商品详情imgs/初音裤子12.jpg",
        "imgs/商品详情imgs/初音裤子13.jpg",
      ],
    },
    {
      bootsname: "初音未来短裤",
      bootsimg: "imgs/商品裤子imgs/初音未来短裤.jpg",
      bootsmoney: "178",
      title: "boots",
      id: 300002,
      climgs: [
        "imgs/商品详情imgs/初音未来短裤1.jpg",
        "imgs/商品详情imgs/初音未来短裤2.jpg",
        "imgs/商品详情imgs/初音未来短裤3.jpg",
        "imgs/商品详情imgs/初音未来短裤4.jpg",
        "imgs/商品详情imgs/初音未来短裤5.jpg",
        "imgs/商品详情imgs/初音未来短裤6.jpg",
        "imgs/商品详情imgs/初音未来短裤7.jpg",
        "imgs/商品详情imgs/初音未来短裤8.jpg",
        "imgs/商品详情imgs/初音未来短裤9.jpg",
        "imgs/商品详情imgs/初音未来短裤10.jpg",
        "imgs/商品详情imgs/初音未来短裤11.jpg",
        "imgs/商品详情imgs/初音未来短裤12.jpg",
      ],
    },
    {
      bootsname: "星尘拼抽绳裤子",
      bootsimg: "imgs/商品裤子imgs/星尘拼抽绳裤子.jpg",
      bootsmoney: "218",
      title: "boots",
      id: 300003,
      climgs: [
        "imgs/商品详情imgs/星尘拼抽绳裤子1.jpg",
        "imgs/商品详情imgs/星尘拼抽绳裤子2.jpg",
        "imgs/商品详情imgs/星尘拼抽绳裤子3.jpg",
        "imgs/商品详情imgs/星尘拼抽绳裤子4.jpg",
        "imgs/商品详情imgs/星尘拼抽绳裤子5.jpg",
        "imgs/商品详情imgs/星尘拼抽绳裤子6.jpg",
        "imgs/商品详情imgs/星尘拼抽绳裤子7.jpg",
        "imgs/商品详情imgs/星尘拼抽绳裤子8.jpg",
        "imgs/商品详情imgs/星尘拼抽绳裤子9.jpg",
        "imgs/商品详情imgs/星尘拼抽绳裤子10.jpg",
        "imgs/商品详情imgs/星尘拼抽绳裤子11.jpg",
      ],
    },
    {
      bootsname: "星尘周边短裤",
      bootsimg: "imgs/商品裤子imgs/星尘周边短裤.jpg",
      bootsmoney: "178",
      title: "boots",
      id: 300004,
      climgs: [
        "imgs/商品详情imgs/星尘周边短裤1.jpg",
        "imgs/商品详情imgs/星尘周边短裤2.jpg",
        "imgs/商品详情imgs/星尘周边短裤3.jpg",
        "imgs/商品详情imgs/星尘周边短裤4.jpg",
        "imgs/商品详情imgs/星尘周边短裤5.jpg",
        "imgs/商品详情imgs/星尘周边短裤6.jpg",
        "imgs/商品详情imgs/星尘周边短裤7.jpg",
        "imgs/商品详情imgs/星尘周边短裤8.jpg",
        "imgs/商品详情imgs/星尘周边短裤9.jpg",
      ],
    },
    {
      bootsname: "狂热蓝调Δ主题工装裤",
      bootsimg: "imgs/商品裤子imgs/狂热蓝调Δ主题工装裤.jpg",
      bootsmoney: "189",
      title: "boots",
      id: 300005,
      climgs: [
        "imgs/商品详情imgs/狂热蓝调Δ主题工装裤1.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题工装裤2.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题工装裤3.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题工装裤4.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题工装裤5.jpg",
        "imgs/商品详情imgs/狂热蓝调Δ主题工装裤6.jpg",
      ],
    },
    {
      bootsname: "魇夜星渊主题牛仔裤",
      bootsimg: "imgs/商品裤子imgs/魇夜星渊主题牛仔裤.jpg",
      bootsmoney: "229",
      title: "boots",
      id: 300006,
      climgs: [
        "imgs/商品详情imgs/魇夜星渊主题牛仔裤1.jpg",
        "imgs/商品详情imgs/魇夜星渊主题牛仔裤2.jpg",
        "imgs/商品详情imgs/魇夜星渊主题牛仔裤3.jpg",
        "imgs/商品详情imgs/魇夜星渊主题牛仔裤4.jpg",
        "imgs/商品详情imgs/魇夜星渊主题牛仔裤5.jpg",
        "imgs/商品详情imgs/魇夜星渊主题牛仔裤6.jpg",
      ],
    },
    {
      bootsname: "薪炎之律者主题针织裤",
      bootsimg: "imgs/商品裤子imgs/薪炎之律者主题针织裤.jpg",
      bootsmoney: "229",
      title: "boots",
      id: 300007,
      climgs: [
        "imgs/商品详情imgs/薪炎之律者主题针织裤1.jpg",
        "imgs/商品详情imgs/薪炎之律者主题针织裤2.jpg",
        "imgs/商品详情imgs/薪炎之律者主题针织裤3.jpg",
        "imgs/商品详情imgs/薪炎之律者主题针织裤4.jpg",
        "imgs/商品详情imgs/薪炎之律者主题针织裤5.jpg",
        "imgs/商品详情imgs/薪炎之律者主题针织裤6.jpg",
      ],
    },
    {
      bootsname: "失落迷迭主题工装裤",
      bootsimg: "imgs/商品裤子imgs/失落迷迭主题工装裤.jpg",
      bootsmoney: "229",
      title: "boots",
      id: 300008,
      climgs: [
        "imgs/商品详情imgs/失落迷迭主题工装裤1.jpg",
        "imgs/商品详情imgs/失落迷迭主题工装裤2.jpg",
        "imgs/商品详情imgs/失落迷迭主题工装裤3.jpg",
        "imgs/商品详情imgs/失落迷迭主题工装裤4.jpg",
        "imgs/商品详情imgs/失落迷迭主题工装裤5.jpg",
        "imgs/商品详情imgs/失落迷迭主题工装裤6.jpg",
      ],
    },
    {
      bootsname: "迷城骇兔主题直筒休闲裤",
      bootsimg: "imgs/商品裤子imgs/迷城骇兔主题直筒休闲裤.jpg",
      bootsmoney: "189",
      title: "boots",
      id: 300009,
      climgs: [
        "imgs/商品详情imgs/迷城骇兔主题直筒休闲裤1.jpg",
        "imgs/商品详情imgs/迷城骇兔主题直筒休闲裤2.jpg",
        "imgs/商品详情imgs/迷城骇兔主题直筒休闲裤3.jpg",
        "imgs/商品详情imgs/迷城骇兔主题直筒休闲裤4.jpg",
        "imgs/商品详情imgs/迷城骇兔主题直筒休闲裤5.jpg",
        "imgs/商品详情imgs/迷城骇兔主题直筒休闲裤6.jpg",
        "imgs/商品详情imgs/迷城骇兔主题直筒休闲裤7.jpg",
      ],
    },
    {
      bootsname: "识之律者针织休闲长裤",
      bootsimg: "imgs/商品裤子imgs/识之律者针织休闲长裤.jpg",
      bootsmoney: "199",
      title: "boots",
      id: 3000010,
      climgs: [
        "imgs/商品详情imgs/识之律者针织休闲长裤1.jpg",
        "imgs/商品详情imgs/识之律者针织休闲长裤2.jpg",
        "imgs/商品详情imgs/识之律者针织休闲长裤3.jpg",
        "imgs/商品详情imgs/识之律者针织休闲长裤4.jpg",
        "imgs/商品详情imgs/识之律者针织休闲长裤5.jpg",
        "imgs/商品详情imgs/识之律者针织休闲长裤6.jpg",
        "imgs/商品详情imgs/识之律者针织休闲长裤7.jpg",
      ],
    },
    {
      bootsname: "天使重构主题工装裤",
      bootsimg: "imgs/商品裤子imgs/天使重构主题工装裤.jpg",
      bootsmoney: "199",
      title: "boots",
      id: 3000011,
      climgs: [
        "imgs/商品详情imgs/天使重构主题工装裤1.jpg",
        "imgs/商品详情imgs/天使重构主题工装裤2.jpg",
        "imgs/商品详情imgs/天使重构主题工装裤3.jpg",
        "imgs/商品详情imgs/天使重构主题工装裤4.jpg",
        "imgs/商品详情imgs/天使重构主题工装裤5.jpg",
        "imgs/商品详情imgs/天使重构主题工装裤6.jpg",
      ],
    },
    {
      bootsname: "八重樱霞影霓踪运动裤",
      bootsimg: "imgs/商品裤子imgs/八重樱霞影霓踪运动裤.jpg",
      bootsmoney: "199",
      title: "boots",
      id: 3000012,
      climgs: [
        "imgs/商品详情imgs/八重樱霞影霓踪运动裤1.jpg",
        "imgs/商品详情imgs/八重樱霞影霓踪运动裤2.jpg",
        "imgs/商品详情imgs/八重樱霞影霓踪运动裤3.jpg",
        "imgs/商品详情imgs/八重樱霞影霓踪运动裤4.jpg",
        "imgs/商品详情imgs/八重樱霞影霓踪运动裤5.jpg",
        "imgs/商品详情imgs/八重樱霞影霓踪运动裤6.jpg",
      ],
    },
    {
      bootsname: "黑羽之鸢系列牛仔长裤",
      bootsimg: "imgs/商品裤子imgs/黑羽之鸢系列牛仔长裤.jpg",
      bootsmoney: "199",
      title: "boots",
      id: 3000013,
      climgs: [
        "imgs/商品详情imgs/黑羽之鸢系列牛仔长裤1.jpg",
        "imgs/商品详情imgs/黑羽之鸢系列牛仔长裤2.jpg",
        "imgs/商品详情imgs/黑羽之鸢系列牛仔长裤3.jpg",
        "imgs/商品详情imgs/黑羽之鸢系列牛仔长裤4.jpg",
        "imgs/商品详情imgs/黑羽之鸢系列牛仔长裤5.jpg",
        "imgs/商品详情imgs/黑羽之鸢系列牛仔长裤6.jpg",
        "imgs/商品详情imgs/黑羽之鸢系列牛仔长裤7.jpg",
      ],
    },
    {
      bootsname: "天使重构短裤",
      bootsimg: "imgs/商品裤子imgs/天使重构短裤.jpg",
      bootsmoney: "139",
      title: "boots",
      id: 3000014,
      climgs: [
        "imgs/商品详情imgs/天使重构短裤1.jpg",
        "imgs/商品详情imgs/天使重构短裤2.jpg",
        "imgs/商品详情imgs/天使重构短裤3.jpg",
        "imgs/商品详情imgs/天使重构短裤4.jpg",
        "imgs/商品详情imgs/天使重构短裤5.jpg",
        "imgs/商品详情imgs/天使重构短裤6.jpg",
        "imgs/商品详情imgs/天使重构短裤7.jpg",
      ],
    },
    {
      bootsname: "舰长装备系列工装裤",
      bootsimg: "imgs/商品裤子imgs/舰长装备系列工装裤.jpg",
      bootsmoney: "139",
      title: "boots",
      id: 3000015,
      climgs: [
        "imgs/商品详情imgs/舰长装备系列工装裤1.jpg",
        "imgs/商品详情imgs/舰长装备系列工装裤2.jpg",
        "imgs/商品详情imgs/舰长装备系列工装裤3.jpg",
        "imgs/商品详情imgs/舰长装备系列工装裤4.jpg",
        "imgs/商品详情imgs/舰长装备系列工装裤5.jpg",
        "imgs/商品详情imgs/舰长装备系列工装裤6.jpg",
        "imgs/商品详情imgs/舰长装备系列工装裤7.jpg",
      ],
    },
  ],

  // cosplay服装的数据
  cosplay: [
    {
      cosplayname: "原神优菈cosplay服装",
      cosplayimg: "imgs/cosplayimgs/尤拉.jpg",
      cosplaymoney: "309",
      title: "cosplay",
      id: 400001,
      climgs: [
        "imgs/商品详情imgs/尤拉cos1.jpg",
        "imgs/商品详情imgs/尤拉cos2.jpg",
        "imgs/商品详情imgs/尤拉cos3.jpg",
        "imgs/商品详情imgs/尤拉cos4.jpg",
        "imgs/商品详情imgs/尤拉cos5.jpg",
        "imgs/商品详情imgs/尤拉cos6.jpg",
        "imgs/商品详情imgs/尤拉cos7.jpg",
        "imgs/商品详情imgs/尤拉cos8.jpg",
        "imgs/商品详情imgs/尤拉cos9.jpg",
        "imgs/商品详情imgs/尤拉cos10.jpg",
        "imgs/商品详情imgs/尤拉cos11.jpg",
        "imgs/商品详情imgs/尤拉cos12.jpg",
        "imgs/商品详情imgs/尤拉cos13.jpg",
        "imgs/商品详情imgs/尤拉cos14.jpg",
        "imgs/商品详情imgs/尤拉cos15.jpg",
        "imgs/商品详情imgs/尤拉cos16.jpg",
        "imgs/商品详情imgs/尤拉cos17.jpg",
      ],
    },
    {
      cosplayname: "明日方舟艾雅法拉cos服",
      cosplayimg: "imgs/cosplayimgs/明日方舟艾雅法拉cos服.jpg",
      cosplaymoney: "349",
      title: "cosplay",
      id: 400002,
      climgs: [
        "imgs/商品详情imgs/明日方舟艾雅法拉cos服1.jpg",
        "imgs/商品详情imgs/明日方舟艾雅法拉cos服2.jpg",
        "imgs/商品详情imgs/明日方舟艾雅法拉cos服3.jpg",
        "imgs/商品详情imgs/明日方舟艾雅法拉cos服4.jpg",
        "imgs/商品详情imgs/明日方舟艾雅法拉cos服5.jpg",
        "imgs/商品详情imgs/明日方舟艾雅法拉cos服6.jpg",
        "imgs/商品详情imgs/明日方舟艾雅法拉cos服7.jpg",
        "imgs/商品详情imgs/明日方舟艾雅法拉cos服8.jpg",
        "imgs/商品详情imgs/明日方舟艾雅法拉cos服9.jpg",
      ],
    },
    {
      cosplayname: "FGO黑贞德cosplay服装",
      cosplayimg: "imgs/cosplayimgs/FGO黑贞德cosplay服装.jpg",
      cosplaymoney: "658",
      title: "cosplay",
      id: 400003,
      climgs: [
        "imgs/商品详情imgs/FGO黑贞德cosplay服装1.jpg",
        "imgs/商品详情imgs/FGO黑贞德cosplay服装2.jpg",
        "imgs/商品详情imgs/FGO黑贞德cosplay服装3.jpg",
        "imgs/商品详情imgs/FGO黑贞德cosplay服装4.jpg",
        "imgs/商品详情imgs/FGO黑贞德cosplay服装5.jpg",
        "imgs/商品详情imgs/FGO黑贞德cosplay服装6.jpg",
        "imgs/商品详情imgs/FGO黑贞德cosplay服装7.jpg",
        "imgs/商品详情imgs/FGO黑贞德cosplay服装8.jpg",
        "imgs/商品详情imgs/FGO黑贞德cosplay服装9.jpg",
        "imgs/商品详情imgs/FGO黑贞德cosplay服装10.jpg",
      ],
    },
    {
      cosplayname: "尼禄saber女仆装cosplay服",
      cosplayimg: "imgs/cosplayimgs/尼禄saber女仆装cosplay服.jpg",
      cosplaymoney: "300",
      title: "cosplay",
      id: 400004,
      climgs: [
        "imgs/商品详情imgs/尼禄saber女仆装cosplay服1.jpg",
        "imgs/商品详情imgs/尼禄saber女仆装cosplay服2.jpg",
        "imgs/商品详情imgs/尼禄saber女仆装cosplay服3.jpg",
        "imgs/商品详情imgs/尼禄saber女仆装cosplay服4.jpg",
        "imgs/商品详情imgs/尼禄saber女仆装cosplay服5.jpg",
        "imgs/商品详情imgs/尼禄saber女仆装cosplay服6.jpg",
        "imgs/商品详情imgs/尼禄saber女仆装cosplay服7.jpg",
        "imgs/商品详情imgs/尼禄saber女仆装cosplay服8.jpg",
        "imgs/商品详情imgs/尼禄saber女仆装cosplay服9.jpg",
        "imgs/商品详情imgs/尼禄saber女仆装cosplay服10.jpg",
        "imgs/商品详情imgs/尼禄saber女仆装cosplay服11.jpg",
        "imgs/商品详情imgs/尼禄saber女仆装cosplay服12.jpg",
      ],
    },
    {
      cosplayname: "酒吞童子cosplay女仆装",
      cosplayimg: "imgs/cosplayimgs/酒吞童子cosplay女仆装.jpg",
      cosplaymoney: "279",
      title: "cosplay",
      id: 400005,
      climgs: [
        "imgs/商品详情imgs/酒吞童子cosplay女仆装1.jpg",
        "imgs/商品详情imgs/酒吞童子cosplay女仆装2.jpg",
        "imgs/商品详情imgs/酒吞童子cosplay女仆装3.jpg",
        "imgs/商品详情imgs/酒吞童子cosplay女仆装4.jpg",
        "imgs/商品详情imgs/酒吞童子cosplay女仆装5.jpg",
        "imgs/商品详情imgs/酒吞童子cosplay女仆装6.jpg",
        "imgs/商品详情imgs/酒吞童子cosplay女仆装7.jpg",
        "imgs/商品详情imgs/酒吞童子cosplay女仆装8.jpg",
        "imgs/商品详情imgs/酒吞童子cosplay女仆装9.jpg",
        "imgs/商品详情imgs/酒吞童子cosplay女仆装10.jpg",
      ],
    },
    {
      cosplayname: "幻梦谭金莲cos服旗袍",
      cosplayimg: "imgs/cosplayimgs/幻梦谭金莲cos服旗袍.jpg",
      cosplaymoney: "309",
      title: "cosplay",
      id: 400006,
      climgs: [
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍1.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍2.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍3.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍4.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍5.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍6.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍7.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍8.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍9.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍10.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍11.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍12.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍13.jpg",
      ],
    },
    {
      cosplayname: "幻梦谭金莲cos服旗袍",
      cosplayimg: "imgs/cosplayimgs/幻梦谭金莲cos服旗袍.jpg",
      cosplaymoney: "309",
      title: "cosplay",
      id: 400006,
      climgs: [
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍1.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍2.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍3.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍4.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍5.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍6.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍7.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍8.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍9.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍10.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍11.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍12.jpg",
        "imgs/商品详情imgs/幻梦谭金莲cos服旗袍13.jpg",
      ],
    },
    {
      cosplayname: "蕾姆拉姆猫咪睡衣cos服装",
      cosplayimg: "imgs/cosplayimgs/蕾姆拉姆猫咪睡衣cos服装.jpg",
      cosplaymoney: "149",
      title: "cosplay",
      id: 400007,
      climgs: [
        "imgs/商品详情imgs/蕾姆拉姆猫咪睡衣cos服装1.jpg",
        "imgs/商品详情imgs/蕾姆拉姆猫咪睡衣cos服装2.jpg",
        "imgs/商品详情imgs/蕾姆拉姆猫咪睡衣cos服装3.jpg",
        "imgs/商品详情imgs/蕾姆拉姆猫咪睡衣cos服装4.jpg",
        "imgs/商品详情imgs/蕾姆拉姆猫咪睡衣cos服装5.jpg",
        "imgs/商品详情imgs/蕾姆拉姆猫咪睡衣cos服装6.jpg",
        "imgs/商品详情imgs/蕾姆拉姆猫咪睡衣cos服装7.jpg",
        "imgs/商品详情imgs/蕾姆拉姆猫咪睡衣cos服装8.jpg",
        "imgs/商品详情imgs/蕾姆拉姆猫咪睡衣cos服装9.jpg",
        "imgs/商品详情imgs/蕾姆拉姆猫咪睡衣cos服装10.jpg",
        "imgs/商品详情imgs/蕾姆拉姆猫咪睡衣cos服装11.jpg",
        "imgs/商品详情imgs/蕾姆拉姆猫咪睡衣cos服装12.jpg",
        "imgs/商品详情imgs/蕾姆拉姆猫咪睡衣cos服装13.jpg",
      ],
    },
    {
      cosplayname: "香子兰cosplay女仆装",
      cosplayimg: "imgs/cosplayimgs/香子兰cosplay女仆装.jpg",
      cosplaymoney: "289",
      title: "cosplay",
      id: 400008,
      climgs: [
        "imgs/商品详情imgs/香子兰cosplay女仆装1.jpg",
        "imgs/商品详情imgs/香子兰cosplay女仆装2.jpg",
        "imgs/商品详情imgs/香子兰cosplay女仆装3.jpg",
        "imgs/商品详情imgs/香子兰cosplay女仆装4.jpg",
        "imgs/商品详情imgs/香子兰cosplay女仆装5.jpg",
        "imgs/商品详情imgs/香子兰cosplay女仆装6.jpg",
        "imgs/商品详情imgs/香子兰cosplay女仆装7.jpg",
        "imgs/商品详情imgs/香子兰cosplay女仆装8.jpg",
        "imgs/商品详情imgs/香子兰cosplay女仆装9.jpg",
        "imgs/商品详情imgs/香子兰cosplay女仆装10.jpg",
        "imgs/商品详情imgs/香子兰cosplay女仆装11.jpg",
        "imgs/商品详情imgs/香子兰cosplay女仆装12.jpg",
        "imgs/商品详情imgs/香子兰cosplay女仆装13.jpg",
      ],
    },
    {
      cosplayname: "巧克力cosplay女仆装",
      cosplayimg: "imgs/cosplayimgs/巧克力cosplay女仆装.jpg",
      cosplaymoney: "289",
      title: "cosplay",
      id: 400009,
      climgs: [
        "imgs/商品详情imgs/巧克力cosplay女仆装1.jpg",
        "imgs/商品详情imgs/巧克力cosplay女仆装2.jpg",
        "imgs/商品详情imgs/巧克力cosplay女仆装3.jpg",
        "imgs/商品详情imgs/巧克力cosplay女仆装4.jpg",
        "imgs/商品详情imgs/巧克力cosplay女仆装5.jpg",
        "imgs/商品详情imgs/巧克力cosplay女仆装6.jpg",
        "imgs/商品详情imgs/巧克力cosplay女仆装7.jpg",
        "imgs/商品详情imgs/巧克力cosplay女仆装8.jpg",
        "imgs/商品详情imgs/巧克力cosplay女仆装9.jpg",
        "imgs/商品详情imgs/巧克力cosplay女仆装10.jpg",
        "imgs/商品详情imgs/巧克力cosplay女仆装11.jpg",
        "imgs/商品详情imgs/巧克力cosplay女仆装12.jpg",
        "imgs/商品详情imgs/巧克力cosplay女仆装13.jpg",
      ],
    },
    {
      cosplayname: "大凤凤鸣春晓旗袍",
      cosplayimg: "imgs/cosplayimgs/大凤凤鸣春晓旗袍.jpg",
      cosplaymoney: "199",
      title: "cosplay",
      id: 400010,
      climgs: [
        "imgs/商品详情imgs/大凤凤鸣春晓旗袍1.jpg",
        "imgs/商品详情imgs/大凤凤鸣春晓旗袍2.jpg",
        "imgs/商品详情imgs/大凤凤鸣春晓旗袍3.jpg",
        "imgs/商品详情imgs/大凤凤鸣春晓旗袍4.jpg",
        "imgs/商品详情imgs/大凤凤鸣春晓旗袍5.jpg",
        "imgs/商品详情imgs/大凤凤鸣春晓旗袍6.jpg",
        "imgs/商品详情imgs/大凤凤鸣春晓旗袍7.jpg",
        "imgs/商品详情imgs/大凤凤鸣春晓旗袍8.jpg",
        "imgs/商品详情imgs/大凤凤鸣春晓旗袍9.jpg",
        "imgs/商品详情imgs/大凤凤鸣春晓旗袍10.jpg",
      ],
    },
    {
      cosplayname: "佩可莉姆cos服",
      cosplayimg: "imgs/cosplayimgs/佩可莉姆cos服.jpg",
      cosplaymoney: "319",
      title: "cosplay",
      id: 400011,
      climgs: [
        "imgs/商品详情imgs/佩可莉姆cos服1.jpg",
        "imgs/商品详情imgs/佩可莉姆cos服2.jpg",
        "imgs/商品详情imgs/佩可莉姆cos服3.jpg",
        "imgs/商品详情imgs/佩可莉姆cos服4.jpg",
        "imgs/商品详情imgs/佩可莉姆cos服5.jpg",
        "imgs/商品详情imgs/佩可莉姆cos服6.jpg",
        "imgs/商品详情imgs/佩可莉姆cos服7.jpg",
        "imgs/商品详情imgs/佩可莉姆cos服8.jpg",
        "imgs/商品详情imgs/佩可莉姆cos服9.jpg",
      ],
    },
    {
      cosplayname: "可可萝cos服",
      cosplayimg: "imgs/cosplayimgs/可可萝cos服.jpg",
      cosplaymoney: "229",
      title: "cosplay",
      id: 400012,
      climgs: [
        "imgs/商品详情imgs/可可萝cos服1.jpg",
        "imgs/商品详情imgs/可可萝cos服2.jpg",
        "imgs/商品详情imgs/可可萝cos服3.jpg",
        "imgs/商品详情imgs/可可萝cos服4.jpg",
        "imgs/商品详情imgs/可可萝cos服5.jpg",
        "imgs/商品详情imgs/可可萝cos服6.jpg",
        "imgs/商品详情imgs/可可萝cos服7.jpg",
        "imgs/商品详情imgs/可可萝cos服8.jpg",
        "imgs/商品详情imgs/可可萝cos服9.jpg",
        "imgs/商品详情imgs/可可萝cos服10.jpg",
        "imgs/商品详情imgs/可可萝cos服11.jpg",
        "imgs/商品详情imgs/可可萝cos服12.jpg",
        "imgs/商品详情imgs/可可萝cos服13.jpg",
        "imgs/商品详情imgs/可可萝cos服14.jpg",
        "imgs/商品详情imgs/可可萝cos服15.jpg",
        "imgs/商品详情imgs/可可萝cos服16.jpg",
      ],
    },
    {
      cosplayname: "泳装佩可莉姆cos服",
      cosplayimg: "imgs/cosplayimgs/泳装佩可莉姆cos服.jpg",
      cosplaymoney: "109",
      title: "cosplay",
      id: 400013,
      climgs: [
        "imgs/商品详情imgs/泳装佩可莉姆cos服1.jpg",
        "imgs/商品详情imgs/泳装佩可莉姆cos服2.jpg",
        "imgs/商品详情imgs/泳装佩可莉姆cos服3.jpg",
        "imgs/商品详情imgs/泳装佩可莉姆cos服4.jpg",
        "imgs/商品详情imgs/泳装佩可莉姆cos服5.jpg",
        "imgs/商品详情imgs/泳装佩可莉姆cos服6.jpg",
        "imgs/商品详情imgs/泳装佩可莉姆cos服7.jpg",
        "imgs/商品详情imgs/泳装佩可莉姆cos服8.jpg",
        "imgs/商品详情imgs/泳装佩可莉姆cos服9.jpg",
        "imgs/商品详情imgs/泳装佩可莉姆cos服10.jpg",
        "imgs/商品详情imgs/泳装佩可莉姆cos服11.jpg",
        "imgs/商品详情imgs/泳装佩可莉姆cos服12.jpg",
      ],
    },
    {
      cosplayname: "伊什塔尔弓凛同人cos服",
      cosplayimg: "imgs/cosplayimgs/伊什塔尔弓凛同人cos服.jpg",
      cosplaymoney: "369",
      title: "cosplay",
      id: 400014,
      climgs: [
        "imgs/商品详情imgs/伊什塔尔弓凛同人cos服1.jpg",
        "imgs/商品详情imgs/伊什塔尔弓凛同人cos服2.jpg",
        "imgs/商品详情imgs/伊什塔尔弓凛同人cos服3.jpg",
        "imgs/商品详情imgs/伊什塔尔弓凛同人cos服4.jpg",
        "imgs/商品详情imgs/伊什塔尔弓凛同人cos服5.jpg",
        "imgs/商品详情imgs/伊什塔尔弓凛同人cos服6.jpg",
        "imgs/商品详情imgs/伊什塔尔弓凛同人cos服7.jpg",
        "imgs/商品详情imgs/伊什塔尔弓凛同人cos服8.jpg",
        "imgs/商品详情imgs/伊什塔尔弓凛同人cos服9.jpg",
        "imgs/商品详情imgs/伊什塔尔弓凛同人cos服10.jpg",
        "imgs/商品详情imgs/伊什塔尔弓凛同人cos服11.jpg",
        "imgs/商品详情imgs/伊什塔尔弓凛同人cos服12.jpg",
        "imgs/商品详情imgs/伊什塔尔弓凛同人cos服13.jpg",
      ],
    },
    {
      cosplayname: "黑枪呆同人cos兔女郎",
      cosplayimg: "imgs/cosplayimgs/黑枪呆同人cos兔女郎.jpg",
      cosplaymoney: "209",
      title: "cosplay",
      id: 400015,
      climgs: [
        "imgs/商品详情imgs/黑枪呆同人cos兔女郎1.jpg",
        "imgs/商品详情imgs/黑枪呆同人cos兔女郎2.jpg",
        "imgs/商品详情imgs/黑枪呆同人cos兔女郎3.jpg",
        "imgs/商品详情imgs/黑枪呆同人cos兔女郎4.jpg",
        "imgs/商品详情imgs/黑枪呆同人cos兔女郎5.jpg",
        "imgs/商品详情imgs/黑枪呆同人cos兔女郎6.jpg",
        "imgs/商品详情imgs/黑枪呆同人cos兔女郎7.jpg",
        "imgs/商品详情imgs/黑枪呆同人cos兔女郎8.jpg",
        "imgs/商品详情imgs/黑枪呆同人cos兔女郎9.jpg",
        "imgs/商品详情imgs/黑枪呆同人cos兔女郎10.jpg",
        "imgs/商品详情imgs/黑枪呆同人cos兔女郎11.jpg",
      ],
    },
  ],
};
